### PR TITLE
Issue-279: Add BT connection timeout/interval config to improve stability

### PR DESCRIPTION
**Pull request by drumwhizz**
Have this mod on the new app and its made a huge difference to the stability of connections

### CODE REVIEW

**Review by mkj121 — APPROVED** [review]

**Review by RobHumphris — COMMENTED** [review]
`SetConnectionTimeoutCommand()` uses a value of `10000` is this likely to remain fixed or would it be better to pass a value that could be adjusted?

**Comment by drumwhizz** [comment]
> `SetConnectionTimeoutCommand()` uses a value of `10000` is this likely to remain fixed or would it be better to pass a value that could be adjusted?

That's the number we pulled from Pete's code. .It works 100%. Not seen and connection failures or unexpected disconnects since applied. I am not going to be playing with numbers I don't understand

**Comment by mkj121** [comment]
This says it will try for 10 seconds to make a connection. The time that you should wait for a connection depends on teh worst case advertising interval of the sensors. Presently all sensors are set to 5 seconds so, by Nyquist this time out should be somewhat more than this. If we ever lengthened the advertising interval then we might need to increase the connection timeout parameter

**Comment by RobHumphris** [comment]
Parameter 8 is `Connect Create Connection Timeout`, it has a default of `5000ms`, which he's increased to 10sec.
I suspect this number is dependent on our device's advertising period.
His other settings are the very minimum value for `Connection Interval Minimum` and `Connection Interval Maximum` - the fact they're at the same value I find, frankly, terrifying.

**Comment by mkj121** [comment]
Pete's code uses (6,6) for the Connection interval

**Comment by RobHumphris** [comment]
`Connection interval minimum` is 6
`Connection interval maximum` is 6 as well.
The notes say `Connection interval maximum` _"must be >= `Connection interval minimum` Final results will be a result of
negotiation between devices." (and vice versa). 
So I am assuming that he's gone to the minimum to let the devices come to their own negotiated timings with a bias towards the lowest vales.

**Pull request merged**
